[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.0"
tokio = { version = "1.15.0", features = ["macros", "rt", "rt-multi-thread"] }
clap = { version = "3.1.0", features = ["derive", "env"] }
console = "0.15.0"
sqlx-cli = "0.6.2"
